// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcuJjiaOzNJpex9ypLZQtuJzJRGK42CD0',
    appId: '1:307016094412:web:0102bbe62cc4af3dc3a869',
    messagingSenderId: '307016094412',
    projectId: 'parfum-store-986b9',
    authDomain: 'parfum-store-986b9.firebaseapp.com',
    storageBucket: 'parfum-store-986b9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7RAyIdr2ElQ48aPmhxPw3Y65I7ia12Dw',
    appId: '1:307016094412:android:2b1ede0b840a6535c3a869',
    messagingSenderId: '307016094412',
    projectId: 'parfum-store-986b9',
    storageBucket: 'parfum-store-986b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLwb0WoELZoTbTXKCaorM1vuxCCr6KBUY',
    appId: '1:307016094412:ios:42d6899b40c8cb18c3a869',
    messagingSenderId: '307016094412',
    projectId: 'parfum-store-986b9',
    storageBucket: 'parfum-store-986b9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLwb0WoELZoTbTXKCaorM1vuxCCr6KBUY',
    appId: '1:307016094412:ios:42d6899b40c8cb18c3a869',
    messagingSenderId: '307016094412',
    projectId: 'parfum-store-986b9',
    storageBucket: 'parfum-store-986b9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcuJjiaOzNJpex9ypLZQtuJzJRGK42CD0',
    appId: '1:307016094412:web:69375b39e44c7eaac3a869',
    messagingSenderId: '307016094412',
    projectId: 'parfum-store-986b9',
    authDomain: 'parfum-store-986b9.firebaseapp.com',
    storageBucket: 'parfum-store-986b9.firebasestorage.app',
  );

}